FROM ubuntu

LABEL author="vladvons@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive

ARG PKG \
    PKG_PHP_VER \
    PKG_PYTHON_VER \
    PKG_POSTGRES_VER \
    PKG_MARIADB \
    PKG_SSH \
    SUPERUSER \
    SUPERUSER_PASSW

ENV PKG=$PKG \
    PKG_PHP_VER=$PKG_PHP_VER \
    PKG_PYTHON_VER=$PKG_PYTHON_VER \
    PKG_POSTGRES_VER=$PKG_POSTGRES_VER \
    PKG_MARIADB=$PKG_MARIADB \
    PKG_SSH=$PKG_SSH \
    SUPERUSER=$SUPERUSER \
    SUPERUSER_PASSW=$SUPERUSER_PASSW

COPY ./script/files/var/www /var/www
VOLUME /var/www

EXPOSE 22 80 3306 5432

COPY ./script /root/script
WORKDIR /root/script

# only on build
RUN ./script.sh build;

# only on run 
CMD ["./script.sh", "run"]
