FROM ubuntu

LABEL author="vladvons@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive

ARG PKG \
    PKG_PHP_VER \
    PKG_PYTHON_VER \
    PKG_POSTGRES_VER \
    PKG_MARIADB \
    PKG_SSH \
    SUPERUSER \
    SUPERUSER_PASSW

ENV PKG=$PKG \
    PKG_PHP_VER=$PKG_PHP_VER \
    PKG_PYTHON_VER=$PKG_PYTHON_VER \
    PKG_POSTGRES_VER=$PKG_POSTGRES_VER \
    PKG_MARIADB=$PKG_MARIADB \
    PKG_SSH=$PKG_SSH \
    SUPERUSER=$SUPERUSER \
    SUPERUSER_PASSW=$SUPERUSER_PASSW

#VOLUME /var/www /var/lib/mysql /var/lib/postgresql
VOLUME /var/www

EXPOSE 22 80 3306 5432

COPY ./docker/files/var/www /var/www

COPY ./docker /root/docker
WORKDIR /root/docker

# only on build
RUN ./docker_build.sh;

# only on run 
CMD ["./docker_run.sh"]
