FROM debian

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update; \
    apt install --yes --no-install-recommends \
        mc htop \
        mariadb-server \
        apache2 libapache2-mod-php apache2-utils \
        php \
        ;
#CMD mc
