{
 "title": "ProxMox",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "influxdb" },
   {
    "name": "hostname",
    "label": "Host",
    "query": "show tag values from system with key=\"nodename\""
   },
   {
    "name": "interfaces",
    "label": "Interfaces",
    "query": "show tag values from nics with key=\"instance\" where instance='eno1'"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  last(uptime) \nFROM \n  system \nWHERE \n  nodename = '$hostname' AND $timeFilter\nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpustat",
     "query": "SELECT \n  cpu \nFROM \n  cpustat \nWHERE \n  host = '$hostname' AND   $timeFilter",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \n  mean(memused)/mean(memtotal)*100 \nFROM \n  memory \nWHERE \n  host = '$hostname' AND  $timeFilter \nGROUP BY \ntime($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk-data",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  mean(used)/mean(total) \nFROM \n  system \nWHERE \n  type = 'dir' AND nodename = '$hostname' AND $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dir" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "amvita" }
     ]
    }
   ]
  },
  {
   "title": "disk-lvmthin",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  mean(used)/mean(total) \nFROM \n  system \nWHERE \n  type = 'lvmthin' AND nodename = '$hostname' AND $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dir" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "amvita" }
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \n  mean(memtotal) \nFROM \n  memory \nWHERE \n  host ='$hostname' AND  $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \n  mean(memfree) \nFROM \n  memory \nWHERE \n  host = '$hostname' AND   $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM / CT",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "object" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "system",
     "query": "SELECT \n  last(uptime) AS \"Uptime\", \n  cpu AS \"Cpu %\", \n  cpus AS \"Cpus\", \n  mem AS \"RAM\", \n  disk AS \"Disk\", \n  status AS \"Status\" \nFROM \n  system \nWHERE \n  nodename = '$hostname' AND $timeFilter \nGROUP BY \n  \"host\", \"object\" \nLIMIT 1",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu" ], "type": "field" },
       { "params": [ "Cpu %" ], "type": "alias" }
      ],
      [
       { "params": [ "cpus" ], "type": "field" },
       { "params": [ "Cpus" ], "type": "alias" }
      ],
      [
       { "params": [ "mem" ], "type": "field" },
       { "params": [ "RAM" ], "type": "alias" }
      ],
      [
       { "params": [ "disk" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxmox Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpustat",
     "query": "SELECT \n  mean(cpu) \nFROM \n  cpustat \nWHERE \n  host = '$hostname' AND  $timeFilter \nGROUP BY\n   time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "ram usage (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \n  mean(memused)/mean(memtotal)*100 \nFROM \n  memory \nWHERE \n  host = '$hostname' AND  $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage (GiB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT \n  mean(memtotal) AS total, \n  mean(memused) AS used, \n  mean(memfree) AS free \nFROM \n  memory \nWHERE \n  host ='$hostname' AND  $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic In / Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nics",
     "query": "SELECT \n  non_negative_derivative(last(receive), 1s) *8 AS \"Download\", \n  non_negative_derivative(last(transmit), 1s) *8 AS \"Upload\"\nFROM \n  nics \nWHERE \n host = '$hostname' AND instance =~ /^en/ AND $timeFilter \nGROUP BY \n  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "transmit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$interfaces$/" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine / Linux LXC Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  mean(cpu) \nFROM \n  system \nWHERE \n  nodename = '$hostname' AND $timeFilter \nGROUP BY\n  time($__interval), host fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  mean(mem) \nFROM \n  system \nWHERE \n  nodename = '$hostname' AND $timeFilter \nGROUP BY \n  time($__interval), host fill(null)",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic In By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  non_negative_derivative(last(netin), 1s) *8 \nFROM \n  system \nWHERE \n  nodename = '$hostname' AND $timeFilter \nGROUP BY\n  time($__interval), host fill(null)",
     "select": [
      [
       { "params": [ "netin" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Out By CT / VM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT \n  non_negative_derivative(last(netout), 1s) *8 \nFROM \n  system \nWHERE \n  nodename = '$hostname' AND $timeFilter \nGROUP BY\n  time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "netout" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "nodename", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}