#!/bin/sh
#---VladVons@gmail.com

### BEGIN INIT INFO
# Provides:        vbox-startvm
# Required-Start:  $local_fs $network $named $time $syslog
# Required-Stop:   $local_fs $network $named $time $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Description:     Starts all VMs
### END INIT INFO

# update-rc.d vbox-startvm defaults 99 01
# http://unibix.ru/prosto_o_slozhnom/rassharivanie-printera-v-ubuntu-dlya-windows-i-naoborot


VMUSER=linux
VM="WinXP"

[ -r /etc/default/vbox-startvm ] && . /etc/default/vbox-startvm

Mass()
{
  cat $File | grep -v "^$\|^#" | \
  while read VM
  do
    VmAutostart $VM 1
  done
}


case "$1" in
  start)
    echo "Starting VM's"
    sudo -H -b -u $VMUSER VBoxHeadless --startvm "$VM"
    sudo -H -b -u $VMUSER VBoxHeadless --start-paused "$VM"
    ;;
  stop)
    echo "Shutting down VM's"
    sudo -H -b -u $VMUSER VBoxManage controlvm "$VM" savestate
    ;;
  status)
    echo "Running VM's list"
    sudo -H -u $VMUSER VBoxManage list runningvms
    ;;
  *)
    echo "Usage: /etc/init.d/vbox-startvm {start|stop|status}"
    exit 1
    ;;
esac

exit 0
